/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gestion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Youness
 */
public class Liste_Enseignants extends javax.swing.JFrame {
    private DefaultTableModel Tens;
    private Statement st7;
    private ResultSet r;

    /**
     * Creates new form Enseignants
     */
    public Liste_Enseignants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enseignants = new javax.swing.JTable();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        math = new javax.swing.JRadioButton();
        pc = new javax.swing.JRadioButton();
        geo = new javax.swing.JRadioButton();
        civil = new javax.swing.JRadioButton();
        msg = new javax.swing.JLabel();
        alert = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        parPpr = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        parNom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Espace_Etudiants");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        enseignants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        enseignants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enseignantsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(enseignants);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veuillez choisir une filiere", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        buttonGroup1.add(math);
        math.setText("MAth/Info");
        math.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathActionPerformed(evt);
            }
        });

        buttonGroup1.add(pc);
        pc.setText("Physique/Chimie");
        pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcActionPerformed(evt);
            }
        });

        buttonGroup1.add(geo);
        geo.setText("Geologie/Biologie");
        geo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geoActionPerformed(evt);
            }
        });

        buttonGroup1.add(civil);
        civil.setText("Genie civil");
        civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geo)
                    .addComponent(civil)
                    .addComponent(math, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pc))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(pc)
                .addGap(31, 31, 31)
                .addComponent(math)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(civil)
                .addGap(18, 18, 18)
                .addComponent(geo)
                .addGap(37, 37, 37))
        );
        jLayeredPane3.setLayer(math, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(pc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(geo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(civil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rechercher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Par PPR");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Par nom");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        parNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parNomActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(25, 25, 25)
                .addComponent(parNom, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jRadioButton1)
                .addGap(25, 25, 25)
                .addComponent(parPpr, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(268, 268, 268))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(parPpr, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(parNom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jButton1))
        );
        jLayeredPane1.setLayer(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(parPpr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(parNom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(msg))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(alert, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jLayeredPane3.getAccessibleContext().setAccessibleName("Veuillez choisir un département");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1053, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enseignantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enseignantsMouseClicked
        // TODO add your handling code here:
        Statement st;
        ResultSet rs;

        try {
            int row = enseignants.getSelectedRow();
            String table_clic =(enseignants.getModel().getValueAt(row, 0).toString());
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "i");
            st = cn.createStatement();
            rs = st.executeQuery("select * from enseignant where cin='"+table_clic+"' ;");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_enseignantsMouseClicked

    private void mathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathActionPerformed
        // TODO add your handling code here:
        msg.setText("Liste des enseignants du departement " +math.getText()+" :");
        Tens = new DefaultTableModel();
        
        Tens.addColumn("CIN");
        Tens.addColumn("PPR");
        Tens.addColumn("Nom");
        Tens.addColumn("Prenom");
        Tens.addColumn("departement");
        Tens.addColumn("Tel");
        Tens.addColumn("Email");
        //Tens.addColumn("Adresse");
        enseignants.setModel(Tens);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "i");
            Tens.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from enseignant where departement ='"+math.getText()+"';");

            while (r.next()) {
                String acin = r.getString("cin");
                String appr = r.getString("ppr");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String adepartement=r.getString("departement");
                //String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                String aemail = r.getString("Email");

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, appr, anom, aprenom, adepartement, atel, aemail};
                Tens.addRow(tab);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_mathActionPerformed

    private void civilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilActionPerformed
        msg.setText("Liste des enseignants du departement "+civil.getText()+" :");     
        Tens = new DefaultTableModel();

        Tens.addColumn("CIN");
        Tens.addColumn("PPR");
        Tens.addColumn("Nom");
        Tens.addColumn("Prenom");
        Tens.addColumn("departement");
        Tens.addColumn("Tel");
        Tens.addColumn("Email");
       // Tens.addColumn("Adresse");
        enseignants.setModel(Tens);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "i");
            Tens.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from enseignant where departement='"+civil.getText()+"';");

            while (r.next()) {
                 String acin = r.getString("cin");
                String appr = r.getString("ppr");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String adepartement=r.getString("departement");
                //String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                String aemail = r.getString("Email");

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, appr, anom, aprenom, adepartement, atel, aemail};
                Tens.addRow(tab);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_civilActionPerformed

    private void geoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geoActionPerformed
        msg.setText("Liste des enseignants du departement "+geo.getText()+" :");
        Tens = new DefaultTableModel();

        Tens.addColumn("CIN");
        Tens.addColumn("PPR");
        Tens.addColumn("Nom");
        Tens.addColumn("Prenom");
        Tens.addColumn("departement");
        Tens.addColumn("Tel");
        Tens.addColumn("Email");
        //Tens.addColumn("Adresse");
        enseignants.setModel(Tens);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "i");
            Tens.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from enseignant where departement='"+geo.getText()+"';");

            while (r.next()) {
                 String acin = r.getString("cin");
                String appr = r.getString("ppr");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String adepartement=r.getString("departement");
                //String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                String aemail = r.getString("Email");

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, appr, anom, aprenom, adepartement, atel, aemail};
                Tens.addRow(tab);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }       
    }//GEN-LAST:event_geoActionPerformed

    private void pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcActionPerformed
         msg.setText("Liste des enseignants du departement "+pc.getText()+" :");
        Tens = new DefaultTableModel();

        Tens.addColumn("CIN");
               Tens.addColumn("PPR");
        Tens.addColumn("Nom");
        Tens.addColumn("Prenom");
        Tens.addColumn("departement");
        Tens.addColumn("Tel");
        Tens.addColumn("Email");
        //Tens.addColumn("Adresse");
        enseignants.setModel(Tens);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "i");
            Tens.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from enseignant where departement='"+pc.getText()+"';");

            while (r.next()) {
                String acin = r.getString("cin");
                String appr = r.getString("ppr");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String adepartement=r.getString("departement");
                //String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                String aemail = r.getString("Email");

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, appr, anom, aprenom, adepartement, atel, aemail};
                Tens.addRow(tab);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_pcActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        esp_etd a = new esp_etd();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
       Tens = new DefaultTableModel();
        
        Tens.addColumn("CIN");
        Tens.addColumn("PPR");
        Tens.addColumn("Nom");
        Tens.addColumn("Prenom");
        Tens.addColumn("departement");
        Tens.addColumn("Tel");
        Tens.addColumn("Email");
        //Tens.addColumn("Adresse");
        enseignants.setModel(Tens);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "i");
            Tens.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from enseignant where nom like'%"+parNom.getText()+"%';");

            while (r.next()) {
                String acin = r.getString("cin");
                String appr = r.getString("ppr");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String adepartement=r.getString("departement");
                //String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                String aemail = r.getString("Email");

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, appr, anom, aprenom, adepartement, atel, aemail};
                Tens.addRow(tab);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void parNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parNomActionPerformed
        // TODO add your handling code here:
       
         

    }//GEN-LAST:event_parNomActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        Tens = new DefaultTableModel();
        
        Tens.addColumn("CIN");
        Tens.addColumn("PPR");
        Tens.addColumn("Nom");
        Tens.addColumn("Prenom");
        Tens.addColumn("departement");
        Tens.addColumn("Tel");
        Tens.addColumn("Email");
        //Tens.addColumn("Adresse");
        enseignants.setModel(Tens);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "i");
            Tens.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from enseignant where ppr like'%"+parNom.getText()+"%';");

            while (r.next()) {
                String acin = r.getString("cin");
                String appr = r.getString("ppr");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String adepartement=r.getString("departement");
                //String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                String aemail = r.getString("Email");

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, appr, anom, aprenom, adepartement, atel, aemail};
                Tens.addRow(tab);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 Tens = new DefaultTableModel();
        
        Tens.addColumn("CIN");
        Tens.addColumn("PPR");
        Tens.addColumn("Nom");
        Tens.addColumn("Prenom");
        Tens.addColumn("departement");
        Tens.addColumn("Tel");
        Tens.addColumn("Email");
        //Tens.addColumn("Adresse");
        enseignants.setModel(Tens);
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "");
            Tens.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from enseignant where nom like'%"+parNom.getText()+"%';");

            while (r.next()) {
                String acin = r.getString("cin");
                String appr = r.getString("ppr");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String adepartement=r.getString("departement");
                //String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                String aemail = r.getString("Email");

                 //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, appr, anom, aprenom, adepartement, atel, aemail};
                Tens.addRow(tab);
            }
        }
            catch(Exception e) { System.out.println(e.getMessage());  };// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enseignants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Liste_Enseignants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton civil;
    private javax.swing.JTable enseignants;
    private javax.swing.JRadioButton geo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton math;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField parNom;
    private javax.swing.JTextField parPpr;
    private javax.swing.JRadioButton pc;
    // End of variables declaration//GEN-END:variables
}
