/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gestion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import Gestion.Ajouter_etd;

/**
 *
 * @author Youness
 */
public class Liste_Etudiants extends javax.swing.JFrame {
    private DefaultTableModel Tetds;
    private Statement st7;
    private ResultSet r;
 

   
    public Liste_Etudiants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Ajouter_etd aj= new Ajouter_etd();
    
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        etudiants = new javax.swing.JTable();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        gi = new javax.swing.JRadioButton();
        ma = new javax.swing.JRadioButton();
        igi = new javax.swing.JRadioButton();
        rtt = new javax.swing.JRadioButton();
        msg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        msg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(204, 0, 102));

        etudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        etudiants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etudiantsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(etudiants);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veuillez choisir une filiere", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        buttonGroup1.add(gi);
        gi.setText("GI");
        gi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giActionPerformed(evt);
            }
        });

        buttonGroup1.add(ma);
        ma.setText("MA");
        ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maActionPerformed(evt);
            }
        });

        buttonGroup1.add(igi);
        igi.setText("IGI");
        igi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igiActionPerformed(evt);
            }
        });

        buttonGroup1.add(rtt);
        rtt.setText("RTT");
        rtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ma)
                    .addComponent(gi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtt))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ma)
                .addGap(36, 36, 36)
                .addComponent(gi)
                .addGap(30, 30, 30)
                .addComponent(igi)
                .addGap(33, 33, 33)
                .addComponent(rtt)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jLayeredPane3.setLayer(gi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(ma, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(igi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(rtt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));

        jButton4.setText("Espace_Etudiants");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        msg1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(msg)
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(msg1)
                .addGap(435, 435, 435))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(msg1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowOpened

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        esp_etd a = new esp_etd();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rttActionPerformed

        msg1.setText("Liste des étudiants RTT :");
        Tetds = new DefaultTableModel();
        Tetds.addColumn("CIN");
        Tetds.addColumn("CNE");
        Tetds.addColumn("Nom");
        Tetds.addColumn("Prenom");
        Tetds.addColumn("Filiere");
        Tetds.addColumn("Email");
        Tetds.addColumn("Tel");
        Tetds.addColumn("Adresse");
        etudiants.setModel(Tetds);
        int nb=0;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "");
            Tetds.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from etudiant where filiere='"+rtt.getText()+"';");

            while (r.next()) {
                jLabel1.setText(null);
                String acin = r.getString("cin");
                int acne = r.getInt("cne");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String filiere=r.getString("filiere");
                String email=r.getString("email");
                String adr =r.getString("adresse");
                String atel = r.getString("Tel");

                nb++;

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, acne, anom, aprenom, filiere, email, atel, adr};
                Tetds.addRow(tab);
            }
            if(nb==0){ jLabel1.setText("Aucun etudiants");  }

        } catch (Exception e) {
            System.out.println(e.getMessage());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_rttActionPerformed

    private void igiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igiActionPerformed

        msg1.setText("Liste des étudiants IGI :");
        Tetds = new DefaultTableModel();
        Tetds.addColumn("CIN");
        Tetds.addColumn("CNE");
        Tetds.addColumn("Nom");
        Tetds.addColumn("Prenom");
        Tetds.addColumn("Filiere");
        Tetds.addColumn("Email");
        Tetds.addColumn("Tel");
        Tetds.addColumn("Adresse");
        etudiants.setModel(Tetds);
        int nb=0;

        try {
            jLabel1.setText("");
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "");
            Tetds.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from etudiant where filiere='"+igi.getText()+"';");

            while (r.next()) {
                String acin = r.getString("cin");
                int acne = r.getInt("cne");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String filiere=r.getString("filiere");
                String email=r.getString("email");
                String adr =r.getString("adresse");
                String atel = r.getString("Tel");

                nb++;

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, acne, anom, aprenom, filiere, email, atel, adr};
                Tetds.addRow(tab);
            }
            if(nb==0){ jLabel1.setText("Aucun etudiants");  }

        } catch (Exception e) {
            System.out.println(e.getMessage());

        }        // TODO add your handling code here:
    }//GEN-LAST:event_igiActionPerformed

    private void maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maActionPerformed

        msg1.setText("Liste des étudiants MA :");
        Tetds = new DefaultTableModel();
        Tetds.addColumn("CIN");
        Tetds.addColumn("CNE");
        Tetds.addColumn("Nom");
        Tetds.addColumn("Prenom");
        Tetds.addColumn("Filiere");
        Tetds.addColumn("Email");
        Tetds.addColumn("Tel");
        Tetds.addColumn("Adresse");
        etudiants.setModel(Tetds);
        int nb=0;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "");
            Tetds.setRowCount(0);
            st7 =cn.createStatement();
            jLabel1.setText("");

            r = st7.executeQuery("select * from etudiant where filiere='"+ma.getText()+"';");

            while (r.next()) {
                String acin = r.getString("cin");
                int acne = r.getInt("cne");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String filiere=r.getString("filiere");
                String email=r.getString("email");
                String adr =r.getString("adresse");
                String atel = r.getString("Tel");
                nb++;

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, acne, anom, aprenom, filiere, email, atel, adr};
                Tetds.addRow(tab);
            }
            if(nb==0){
                jLabel1.setText("Aucun etudiants");
            }

        } catch (Exception e) {

            System.out.println(e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_maActionPerformed

    private void giActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giActionPerformed
        // TODO add your handling code here:
        msg1.setText("Liste des étudiants GI :");
        Tetds = new DefaultTableModel();
        Tetds.addColumn("CIN");
        Tetds.addColumn("CNE");
        Tetds.addColumn("Nom");
        Tetds.addColumn("Prenom");
        Tetds.addColumn("Filiere");
        Tetds.addColumn("Email");
        Tetds.addColumn("Tel");
        Tetds.addColumn("Adresse");
        etudiants.setModel(Tetds);
        int nb=0;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "");
            Tetds.setRowCount(0);
            st7 =cn.createStatement();

            r = st7.executeQuery("select * from etudiant where filiere='"+gi.getText()+"';");

            jLabel1.setText("");
            while (r.next()) {
                String acin = r.getString("cin");
                int acne = r.getInt("cne");
                String anom =r.getString("nom");
                String aprenom =r.getString("prenom");
                String filiere=r.getString("filiere");
                String email=r.getString("email");
                String atel = r.getString("Tel");
                String adr =r.getString("adresse");
                nb++;

                //Object[] tab = {r.getString("cin"), r.getInt("cne"), r.getString("nom"), r.getString("prenom"), r.getInt("Tel"), r.getString("adresse")};
                Object tab[] ={acin, acne, anom, aprenom, filiere, email, atel, adr};
                Tetds.addRow(tab);
            }
            if(nb==0){ jLabel1.setText("Aucun etudiants"); }
        } catch (Exception e) {
            System.err.println(e.getMessage());

        }
    }//GEN-LAST:event_giActionPerformed

    private void etudiantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etudiantsMouseClicked
        // TODO add your handling code here:
        Statement st;
        ResultSet rs;

        try {
            int row = etudiants.getSelectedRow();
            String table_clic =(etudiants.getModel().getValueAt(row, 0).toString());
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/gestionformation", "root", "");
            st = cn.createStatement();
            rs = st.executeQuery("select * from etudiant where cin='"+table_clic+"';");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_etudiantsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Liste_Etudiants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTable etudiants;
    private javax.swing.JRadioButton gi;
    private javax.swing.JRadioButton igi;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton ma;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel msg1;
    private javax.swing.JRadioButton rtt;
    // End of variables declaration//GEN-END:variables
}
